### ISSUE TITLE
AccessTokenClientCredentialsRequest.User should not return null

### ISSUE THREAD

**Issue by bahrens** [DotNetOpenAuth/DotNetOpenAuth#104]
The AccessTokenClientCredentialsRequest.User property should not return null. Returning null causes the access token to not have a user as a part of it's data. This has the downstream impact of not being able to identify a user for this access token when it reaches the resource server. This also causes the ResourceServer.VerifyAccess to throw an exception when it attempts to create an OAuthPrincipal because it violates the precondition on the OAuthIdentity of username not being null or empty. The suggested fix would be to have the AccessTokenClientCredentialsRequest.User property to return the client identifier instead of null.

**Comment by AArnott** [comment]
Since we're going to expose the `client_id` in the access token to the Resource Server after all, I think we should keep the User property null, but get the rest of the system to handle that appropriately. The RS will have to be prepared for access tokens that describe _either_ users _or_ clients, if they support both.
