### ISSUE TITLE
nuget: Duplicate reporting element

### ISSUE THREAD

**Issue by rcollette** [DotNetOpenAuth/DotNetOpenAuth#148]
If the project .config file already contains <reporting enabled="false">, such as after removing dotnetopenauth, when re-adding dotnetopenauth (unified in this specific case), a duplicate reporting element is added with enabled="true".

It would be nice if the configuration present in the config was left intact except to add any new required configuration elements.

**Comment by AArnott** [comment]
This would be a bug for nuget rather than DNOA. Can you file one with
them as well?

Sent from my Windows Phone
From: Richard Collette
Sent: 5/15/2012 12:03 PM
To: Andrew Arnott
Subject: [dotnetopenid] nuget: Duplicate reporting element (#148)
If the project .config file already contains <reporting
enabled="false">, such as after removing dotnetopenauth, when
re-adding dotnetopenauth (unified in this specific case), a duplicate
reporting element is added with enabled="true".

It would be nice if the configuration present in the config was left
intact except to add any new required configuration elements.

---

Reply to this email directly or view it on GitHub:
https://github.com/AArnott/dotnetopenid/issues/148

**Comment by rcollette** [comment]
I filed the bug report here
http://nuget.codeplex.com/workitem/2207

**Comment by Eonasdan** [comment]
I just got the 

``` 'xml
<reporting enabled="true" />
```

added to be web.config file after updating the nuget package. The node, of course, was already there

**Comment by rcollette** [comment]
XDT support has been added to Nuget.  Perhaps this issue can be addressed now.
