### ISSUE TITLE
IAuthorizationServerHost.CreateAccessToken should include a parameter with the authorizing user and client

### ISSUE THREAD

**Issue by AArnott** [DotNetOpenAuth/DotNetOpenAuth#219]
Currently the AccessTokenResult CreateAccessToken(IAccessTokenRequest accessTokenRequestMessage); method on the IAuthorizationServerHost interface doesn't include information about the user or client

**Comment by jezzsantos** [comment]
I don't think this is fixed in 4.3 (Ultimate). The IAccessTokenRequest.UserName property does exist, but it is null when calling CreateAccessToken() from a call to WebServerClient.RefreshAuthorization().

The workaround here: https://groups.google.com/d/msg/dotnetopenid/PTO8VwYWMXM/7auw25u44bgJ works, which makes me think the bug is still there.
Or perhaps I am not doing something important in my implementation of IAuthorizationServerHost to make it be not-null in CreateAccessToken()?
