### ISSUE TITLE
Add ability to get signature for a request

### ISSUE THREAD

**Issue by andyfmiller** [DotNetOpenAuth/DotNetOpenAuth#224]
The LTI spec from IMS Global Consortium requires an OAuth 1.0 style signature, but no tokens, etc. I am currently using OAuth.Net to calculate the signature as shown below. This works just fine, but I will be adding full OAuth support to the site soon using DotNetOpenAuth and I would like to retire OAuth.Net. It looks like all the methods in DotNetOpenAuth that calculate signatures are protected. Is there a way for me to use DotNetOpenAuth to get the signature? Here is what I do with OAuth.Net:

```
            const string oauth_callback = "about:blank";
            const string oauth_signature_method = "HMAC-SHA1";
            const string oauth_version = "1.0";

            // Calculate the timestamp and nonce
            var ts = DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, 0);
            var timestamp = Convert.ToInt64(ts.TotalSeconds).ToString();
            var nonce = Guid.NewGuid().ToString("N");

            // Set the parameters
            var parameters = new OAuthParameters();
            parameters.Callback = oauth_callback;
            parameters.ConsumerKey = consumerKey;
            parameters.Nonce = nonce;
            parameters.SignatureMethod = oauth_signature_method;
            parameters.Timestamp = timestamp;
            parameters.Version = oauth_version;

            // Calculate the signature
            var signatureBase = SignatureBase.Create("POST", url, parameters);
            var signatureProvider = new HmacSha1SigningProvider();
            var signature = signatureProvider.ComputeSignature(signatureBase, secret, string.Empty);
```

**Comment by AArnott** [comment]
Fixed by 06a2c8d4001.

The new `DelegatingHandler` derived types (listed below) not only allow you to sign any outgoing HTTP request using OAuth 1 rules, with or without an access token, but they also have an `ApplyAuthorization` method that can be used to obtain a signature without actually sending the message. 

The three new classes are:
1. OAuth1HmacSha1HttpMessageHandler
2. OAuth1PlainTextMessageHandler
3. OAuth1RsaSha1HttpMessageHandler
