### ISSUE TITLE
OpenId Realm automatically adds trailing slash

### ISSUE THREAD

**Issue by SLaks** [DotNetOpenAuth/DotNetOpenAuth#227]
I'm using DotNetOpenAuth to provide OpenID login in a rewrite of an existing site.

The OpenID realm from the existing site is a domain name without the trailing slash.  
When I try to use DotNetOpenAuth, .Net's Uri parser automatically adds the slash (for a non-empty path), making it impossible for me to use my original realm.

**Comment by SLaks** [comment]
The fix is to return `this.uri.OriginalString` rather than `AbsoluteUri` from `Realm.ToString()`.

I don't know how much else this will affect.

Note that this is a breaking change for people who have been omitting the slash from their realms.

**Comment by AArnott** [comment]
Hi Slaks,

I'm actually a bit surprised that such a realm as one without the '/'
character in the path can work. OpenID RP discovery mandates that no
redirects occur during discovery, and since a URL without a path isn't
actually valid (think about it--you can't do an HTTP GET without a path
after it, AFAIK), the slash really is a necessary part.

Anyway, that's really not going to help you though, since as you say, it's
a breaking change at this point for you to switch.  I don't think we can
change the behavior of Realm to suit you however, as normalizing the URL is
as much a potentially depended upon behavior by DNOA sites as your site
depends on no trailing slash.

A likely simple workaround you can use is to modify the redirect URL
yourself after you call DNOA's OpenIdRelyingParty.CreateRequest method to
change the value for the realm before sending it back to the browser.

Will that work for you?

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by SLaks** [comment]
I would assume that it works because Google (our OP) normalizes the URI before sending the discovery request.  
It definitely does not treat the two realms as equivalent (that's how I found the bug)

You mean to modify the `OutgoingWebResponse.Headers[HttpResponseHeader.Location]`? I hadn't thought of that.

I already have a modified build of DNOA, so I wont't bother (especially because I dislike mucking about with third-party objects like that)

**Comment by AArnott** [comment]
Yes, I mean just modify the outbound URL to remove the trailing slash from
the one parameter. Modifying DNOA is risky business -- people who do it
often end up opening security holes.

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre
