### ISSUE TITLE
ResourceServer.GetPrincipal Throws FormatException When Bearer Header is Empty or Invalid In Lieu of SecurityTokenValidationException

### ISSUE THREAD

**Issue by davidbitton** [DotNetOpenAuth/DotNetOpenAuth#230]
Shouldn't this throw a SecurityTokenValidationException with the FormatException as the InnerException?

**Comment by AArnott** [comment]
The ResourceServer should not throw a FormatException, but it shouldn't throw a SecurityTokenValidationException either because that doesn't help the ResourceServer comply with the OAuth 2 spec for resource servers. Nor does it conform to the DotNetOpenAuth rule of always throwing a derived type of `ProtocolException`. 
In particular, this call should throw `ProtocolFaultResponseException` as it does for other invalid cases.

**Comment by davidbitton** [comment]
That makes sense. Thanks!

Sent from my iPad

On Nov 11, 2012, at 12:08 AM, Andrew Arnott notifications@github.com
wrote:

The ResourceServer should not throw a FormatException, but it shouldn't
throw a SecurityTokenValidationException either because that doesn't help
the ResourceServer comply with the OAuth 2 spec for resource servers. Nor
does it conform to the DotNetOpenAuth rule of always throwing a derived
type of ProtocolException.
In particular, this call should throw ProtocolFaultResponseException as it
does for other invalid cases.

—
Reply to this email directly or view it on
GitHubhttps://github.com/DotNetOpenAuth/DotNetOpenAuth/issues/230#issuecomment-10263325.
