### ISSUE TITLE
Fix accidental breaking change in OAuth

### ISSUE THREAD

**Issue by AArnott** [DotNetOpenAuth/DotNetOpenAuth#251]
As [reported on StackOverflow](http://stackoverflow.com/questions/15088985/oauthwebsecurity-isauthenticatedwithoauth-method-not-found), this [breaking change](https://github.com/DotNetOpenAuth/DotNetOpenAuth/commit/a6a77cfd131282a8c3f69e8264eb35c08ac17532#src/DotNetOpenAuth.AspNet/OpenAuthSecurityManager.cs) causes a MissingMethodException:

'Microsoft.Web.WebPages.OAuth.OAuthWebSecurity.IsAuthenticatedWithOAuth' threw an exception of type 'System.MissingMethodException' "Method not found: 'Void DotNetOpenAuth.AspNet.OpenAuthSecurityManager..ctor(System.Web.HttpContextBase)'." " at Microsoft.Web.WebPages.OAuth.OAuthWebSecurity.GetIsAuthenticatedWithOAuthCore(HttpContextBase context)\r\n at Microsoft.Web.WebPages.OAuth.OAuthWebSecurity.get_IsAuthenticatedWithOAuth()"

We need to bring that public constructor back!

**Comment by nikolawannabe** [comment]
I'm having this problem too.  Attempting to revert to the 4.0.4.12182 version.

**Comment by nikolawannabe** [comment]
Reverting to the 4.0.4.12182 version as suggested in the StackOverflow post does not work for me because there is no version 4.0.4.12182 for dotnetopenauth.oauth2.core and dotnetopenauth.oauth2.client, and I have built my authorization server with the 2.0 version of the oauth protocol.  I don't see any analogous nuget version for these libraries.

**Comment by phw** [comment]
This affects me too in exactly the same situation (I'm forced to use DotNetOpenAuth 4.2 for the oAuth2 functonallity, but I still need to integrate it into MVC4). I've fixed this for me by using a custom patched Microsoft.Web.WebPages.OAuth.dll.

The whole situation is caused by Microsoft.Web.WebPages.OAuth need of validating a oAuth request given only a HttpContextBase, see https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/Microsoft.Web.WebPages.OAuth/OAuthWebSecurity.cs#L399

Maybe DotNetOpenAuth should provide a cleaner API for this use case, maybe by exposing a static version of IsAuthenticatedWithOpenAuth. But nevertheless, this reverting fix should be applied
