### ISSUE TITLE
DotNetOpenAuth support OpenId login with facebook  ?  V4.2

### ISSUE THREAD

**Issue by honeypc** [DotNetOpenAuth/DotNetOpenAuth#255]
I using DotNetOpenAuth for my website . DotNetOpenAuth action good with Google and Yahoo but Facebook not login with DotNetOpenAuth

**Comment by AArnott** [comment]
Facebook doesn't support OpenID. So that's why it's not working for you.

Logging in with facebook requires that you write some extra code in your
app, and use the OAuth2 support in DotNetOpenAuth. Check out the
OAuthConsumer sample's facebook.aspx page.

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by honeypc** [comment]
OAuthConsumer sample's  not exist file facebook.aspx page. Please check update sample

**Comment by AArnott** [comment]
Quite right: it's in the OAuth_Client_ sample. See
herehttps://github.com/DotNetOpenAuth/DotNetOpenAuth/blob/v4.2/samples/OAuthClient/Facebook.aspx
.

## 

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

**Comment by honeypc** [comment]
```
using DotNetOpenAuth.ApplicationBlock;
using DotNetOpenAuth.ApplicationBlock.Facebook;
```

I can't find two class that ? Please help me

**Comment by AArnott** [comment]
The ApplicationBlock namespace is available with the samples that you can download from http://sf.net/projects/dnoa 
Facebook is not a namespace, so that syntax will never work.

Please submit future questions to the dotnetopenid@googlegroups.com mailing list. This is an issues list for bugs only.
