### ISSUE TITLE
Consider dual-licensing under Apache 2.0?

### ISSUE THREAD

**Issue by lilith** [DotNetOpenAuth/DotNetOpenAuth#347]
The Ms-Pl is incompatible with many free software licenses, as it imposes a unique restriction:

> (D) If you distribute any portion of the software in source code form, you may do so **only under this license** by including a complete copy of this license with your distribution. [...]

Many OSI-approved copyleft licenses require that linking or interacting code must be licensed in a manner that does not further restrict user rights. This conflicts with the Ms-Pl, as it specifically prohibits the right to re-license.

There are many GPL, LGPL, and AGPL-licensed libraries - yet we are forced to choose between using them - and using this library. We are also prevented from using any copyleft license in software which depends on DotNetOpenAuth.

Dual-licensing (or-relicensing) under Apache 2 would solve this. As GitHub notifies people who are mentioned, re-licensing would involve pasting the list of contributors into this thread and asking for a release of their copyright. Getting approval can take anywhere from a few days to several months, depending upon contributor awareness. 

Thoughts?

**Comment by AArnott** [comment]
I'm the copyright holder of ~99% of the code here. So getting approval from everyone involved wouldn't take too long.
That said, I'm not a fan of copyleft because it restricts your freedom such as in the case you just gave. So I'm not inclined to help it further by relicensing. 

But I pass kudos to you for being conscientious about licensing and wanting to do the right and legal thing.
