### ISSUE TITLE
Access tokens are too long

### ISSUE THREAD

**Issue by artema** [DotNetOpenAuth/DotNetOpenAuth#354]
A typical setup (such as in the examples project) produces tokens longer than 512 bytes. Tokens with extra data may be even longer, around 1 KB. Using smaller signing/encryption certificates helps a bit. Is there a way to make access tokens smaller? A customizable token encryption/decryption process would be nice.

**Comment by AArnott** [comment]
Yes. DNOA is pluggable so you can replace the serialization/deserialization of the token so that you can effectively store the full token in a database somewhere and just return a handle to it that is much shorter. I don't remember exactly what API it is, but if you need help finding it you can try emailing the dotnetopenauth@googlegroups.com mailing list.
