### ISSUE TITLE
Bucket names

### ISSUE THREAD

**Issue by jeffijoe** [DotNetOpenAuth/DotNetOpenAuth#369]
I am trying to store my crypto keys in Azure Table Storage, using the Bucket as the PartitionKey, and Handle as the RowKey.

The problem is, those 2 cannot contain `/`, which the bucket names do (`https://localhost/...`). Is it safe for me to do something like this?

```
if(bucket == "https://localhost/dnoa/oauth_refresh_token")
  bucket = "refreshtoken";
else if(bucket == "https://localhost/...") ...
```

Is it possible to configure the names for the buckets?

I tried Uri Escaping the bucket names, but that made them non queryable in Table Storage.

**Comment by jeffijoe** [comment]
I got away with it by base64-encoding it. Still though, would be nice to be able to customize them. Or atleast make them more "safe". :)

**Comment by AArnott** [comment]
Bucket names are always based on URLs. In the two cases you have identified
they are simply "localhost" so I know they appear like they could be
anything (including something without slashes or colons). But in other
cases they are URLs because they represent other servers. So in fact you
should absolutely prepare your code to deal with bucket names that have all
the characters a URL can have. So I believe our fix of base64 encoding them
is a good approach.
However base64 includes two characters that aren't totally "web safe".
That's why a web-safe variant of base64 exists that changes two of the
characters used in the encoded form. You may want to use at instead.

**Comment by AArnott** [comment]
see https://code.google.com/p/stringencoders/wiki/WebSafeBase64 for more information

**Comment by jeffijoe** [comment]
Yeah, I am using a class that does this.
