### ISSUE TITLE
Facebook sample code recommendation...

### ISSUE THREAD

**Issue by mhassman** [DotNetOpenAuth/DotNetOpenAuth#43]
Hi Andrew,

Thought I'd share a recent work-around... facebook doesn't return "expires_in" and therefore all generated access tokens are without an expiration value.

I ended up overloading ProcessUserAuthorization() to transfer epoch time from the token to the AuthorizationState object.
figured this might help someone in the future..

reference info:
http://www.quora.com/Do-the-OAuth2-access-tokens-in-the-new-Facebook-Graph-API-expire

-Mark

**Comment by AArnott** [comment]
Please feel free to contribute the code back (perhaps as a comment on this issue or by forking the project and sending a pull request) and reopen the issue so that it can be applied to the code base.

Thanks for the idea.

**Comment by Crypth** [comment]
Hi!

It seems it not quite as simple as @mhassman suggests, since the first request doesn't contain the access token and it's validity. It's somewhat murky. 

That data is _ignored_ in the ClientBase.UpdateAuthorizationWithResponseAsync when we convert the code to an access token. When it updates the authorizationState, the rest of the message (ExtraData) in the AccessTokenSucessResponse from FB is dropped there and the state is just updated with what we got. 

I suggest the ExtraData should just as well be a part of the AuthorizationState, since it's parsed anyway.

That would still need an overload of the ProcessUserAuthorization which is a bit tricky in it self since lots of classes are marked internal, but not at all impossible, and after retrieving the access token just add the fb expires datetime to the token before returning the IAuthorizationState.
