### ISSUE TITLE
.Net 4.0 version

### ISSUE THREAD

**Issue by NN---** [DotNetOpenAuth/DotNetOpenAuth#55]
Please provide also the library built only for .Net 4.0 . (Not only for .Net 3.5)

Thanks.

**Comment by AArnott** [comment]
Please reopen with your scenario. (i.e. why is this important to you?).

**Comment by NN---** [comment]
First, if you don't have .Net 3.5 on the computer you cannot use this library.

I have .Net 4.0 project and I don't want to load both 3.5 and 4.0 at the same time.

**Comment by AArnott** [comment]
What error are you seeing on a computer with only .NET 4.0 installed?  .NET
4.0 loads .NET 3.5 compiled assemblies just fine by design, and consistent
with my experience.
When you say load both 3.5 and 4.0, what do you mean?  .NET doesn't load a
whole additional CLR or double assemblies just because a 3.5 compiled dll
gets loaded.

**Comment by NN---** [comment]
Actually my problem is something different.
I use Nemerle programming language and its compiler can compile only  3.5 assemblies or only 4.0 assemblies but not mixed.
It is a bug in the compiler and will be fixed soon , but currently I cannot compile my 4.0 project with 3.5 assembly.

**Comment by NN---** [comment]
Is it possible to build a full .Net 4.0 DotNetAuth without any reference to .Net 2.0. for me ?:)

Thanx.

**Comment by AArnott** [comment]
Yes, the source tree has a switch to build to CLR 4 that should help you.
 Right now I'm having trouble building myself because I just reinstalled

## Windows.  I'll let you know when I have a CLR 4 version built.

Andrew Arnott
"I [may] not agree with what you have to say, but I'll defend to the death
your right to say it." - S. G. Tallentyre

On Sun, Nov 27, 2011 at 1:29 PM, NN <
reply@reply.github.com

**Comment by AArnott** [comment]
Here you go:

https://skydrive.live.com/?cid=063d0c265f96e43d&sc=documents&uc=1&id=63D0C265F96E43D%21511#

**Comment by NN---** [comment]
Thanx man.
As I see it's not enough.
You are using log4net which must be compiled for .Net 4.0 too.
I try to compile all by myself, just tell me which branch should I take ? 3.4 or master ?

There is another problems, DotNetOpenAuth.dll doesn't pass verification (PEVerify). :(

**Comment by AArnott** [comment]
The next release will ship targeting _both_ .NET 4.0 and .NET 3.5 compiled assemblies.
