### ISSUE TITLE
Relative Uri in request

### ISSUE THREAD

**Issue by NN---** [DotNetOpenAuth/DotNetOpenAuth#59]
```
// Authorization using OAuth2
var scope = new[] { "scope1" };
var returnTo = new Uri("relative.html", UriKind.Relative);
myClient.RequestUserAuthorization(scope, null, returnTo)
```

This code doesn't work because library expects only absolute URLs.
I don't think there are issues to support also relative ones.

Thanx.

**Comment by NN---** [comment]
It is very easy to do.

1.
Method in UriUtil.cs:

```
        /// <summary>
        /// Uses absolute or relative uri.
        /// </summary>
        /// <param name="uri"></param>
        /// <returns>String representing the uri</returns>
        internal static string GetAbsoluteOrRelativeUri(this Uri uri)
        {
            if (uri.IsAbsoluteUri) return uri.AbsoluteUri;
            else                   return uri.ToString();
        }
```

2.
DotNetOpenAuth\Messaging\Reflection\MessagePart.cs

```
pubilc  MessagePart()
{
  ...
  Map<Uri>(uri => uri.GetAbsoluteOrRelativeUri(), uri => uri.OriginalString, safeUri);
}
```

3.
DotNetOpenAuth\OAuth2\Messages\EndUserAuthorizationRequest.cs

Remove check for absolute Uri.

```
protected override void EnsureValidMessage() {
  ...
 // ErrorUtilities.VerifyProtocol(this.Callback == null || this.Callback.IsAbsoluteUri, this, OAuthStrings.AbsoluteUriRequired, Protocol.redirect_uri);
}   
```

4.
Same in other places.

**Comment by AArnott** [comment]
This requirement for absolute URIs is By Design.  For several reasons, including security, absolute URLs are required by the OAuth spec.  
Also, Uri.AbsoluteUri is _not_ equivalent to Uri.ToString() (see http://blog.nerdbank.net/2008/04/uriabsoluteuri-and-uritostring-are-not.html) so it is not OK to just use the other one when a relative URL is detected.
You should simply create absolute URLs out of your relative ones before passing them to the library.

**Comment by NN---** [comment]
I see.
Ok, I'll try to find workaround using absolute URI.
